src/federica_crawler/apps/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('button_actions/', views.buttons, name='scrape'),
]

src/federica_crawler/federica_crawler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.courses.urls')),
    path('admin/', admin.site.urls),
]

src/federica_crawler/apps/courses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _


class Status(models.Model):
    """This model represent a Course Status"""

    value = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = _("Status")
        verbose_name_plural = _("Statuses")

    def __str__(self):
        return self.value


class Area(models.Model):
    """This model represent a Course area"""
    value = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = _("Area")
        verbose_name_plural = _("Areas")

    def __str__(self):
        return self.value


class Teacher(models.Model):
    """This model represent a Course teacher"""

    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")

    def __str__(self):
        return self.name


class Course(models.Model):
    """This model represent a single Course"""

    title = models.CharField(max_length=200)
    url = models.URLField(blank=True, default='')
    area = models.ForeignKey('Area', on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey('Status', on_delete=models.SET_NULL, null=True)
    teacher = models.ForeignKey(
        'Teacher', on_delete=models.SET_NULL, null=True)
    short_description = models.CharField(
        max_length=300, blank=True, default='')
    description = models.CharField(max_length=1000, blank=True, default='')

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

    def __str__(self):
        return self.title

src/federica_crawler/apps/courses/views.py
from django.views import generic
from django.template.response import TemplateResponse
from .models import Course
from apps.crawler.run_crawler import collect_data


class IndexView(generic.ListView):
    template_name = 'courses/index.html'
    context_object_name = 'courses'

    def get_queryset(self):
        """Return all Courses."""
        return Course.objects.order_by('title')


class DetailView(generic.DetailView):
    model = Course
    template_name = 'courses/detail.html'


def buttons(request):
    """Return a ButtonAction instance that manage all the various buttons"""
    return ButtonActions(request)


class ButtonActions(TemplateResponse):
    """Read which button has been clicked from the response and execute the required actions rendering the right template"""

    def scrape(self):
        """Call scrapy crawler with the right parameters from form"""
        deep=None
        if self.request.GET.get('deepCheck'):
            deep = 'True'
        
        language = self.request.GET.get('languageSelect')
        lang=None
        if language:
            lang = language

        collect_data(deep=deep, lang=lang)
        self.template_name = 'courses/actions/scrape.html'

    def delete(self):
        """Delete all courses from the db"""
        Course.objects.all().delete()
        self.template_name = 'courses/actions/delete.html'

    def __init__(self, request):
        self.request = request
        if self.request.GET.get('scrape'):
            self.scrape()
        if self.request.GET.get('delete'):
            self.delete()
        super().__init__(request, self.template_name)

src/federica_crawler/apps/courses/templates/courses/actions/delete.html
{% extends 'courses/base.html' %}

{% block title %}{{ block.super }} - Delete{% endblock title %}

{% block content %}
All courses have been deleted, {% include 'courses/partials/go_back.html' %}
{% endblock content %}

src/federica_crawler/apps/courses/templates/courses/actions/scrape.html
{% extends 'courses/base.html' %}

{% block title %}{{ block.super }} - Scrape{% endblock title %}

{% block content %}
All data has been scraped, {% include 'courses/partials/go_back.html' %}
{% endblock content %}

src/federica_crawler/apps/courses/templates/courses/base.html
<!doctype html>
<html lang='en'>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Code Challenge{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body class="py-4">
<div class="container">
    {% block content %}{% endblock content %}
    {% block bootstrap_js %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>{% endblock bootstrap_js %}
</div>
</body>

</html>

src/federica_crawler/apps/courses/templates/courses/detail.html
{% extends 'courses/base.html' %}

{% block title %}{{ block.super }} - {{ course.title }}{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ course.title }}</h5>
        <h5 class="card-subtitle mb-2 text-muted">{{ course.teacher }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ course.area }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">{{ course.status }}</h6>
        <p class="card-text">
            {% if course.description %}
                {{ course.description }}
            {% else %}
                {{ course.short_description }}
            {% endif %}
        </p>
        <a href="{{ course.url }}" class="card-link">Course page</a>
    </div>
</div>

{% include 'courses/partials/go_back.html' %}
{% endblock content %}

src/federica_crawler/apps/courses/templates/courses/index.html
{% extends 'courses/base.html' %}

{% block content %}
<form action="button_actions" method="GET">
    <fieldset>
        <legend>Dataset actions</legend>
        <div class="mb-3">
            <label for="languageSelect" class="form-label">Select scraping language</label>
            <select id="languageSelect" name="languageSelect" class="form-select">
                <option disabled selected>--Select language for scraped website--</option>
                <option value="en">English</option>
                <option value="it">Italiano</option>
            </select>
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="deepCheck" name="deepCheck">
                <label class="form-check-label" for="deepCheck">
                    Execute deep scraping (may take really long time, or could be blocked because of too many requests)
                </label>
            </div>
        </div>
        <input type="submit" class="btn btn-primary" name="scrape" value="Scrape new data">
        <input type="submit" class="btn btn-primary" name="delete" value="Delete Courses">
    </fieldset>
</form>

<table class="table table-striped mt-5">
    <caption>Courses list</caption>
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Area</th>
            <th scope="col">Status</th>
            <th scope="col">Teacher</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <th scope="row"><a href="{% url 'courses:detail' course.id %}">{{ course.title }}</a></th>
            <td>{{ course.area }}</td>
            <td>{{ course.status }}</td>
            <td>{{ course.teacher }}</td>
            <td>{{ course.short_description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

src/federica_crawler/apps/courses/templates/courses/partials/go_back.html
go back to <a href="{% url 'courses:index' %}">courses list</a>

src/federica_crawler/apps/courses/templates/courses/scraping.html
All data has been scraped, {% include 'courses/partials/go_back.html' %}